\c travel_op;

DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS users;

--USERS TABLE FOR AUTHENTIFICATION
CREATE TABLE IF NOT EXISTS users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) NOT NULL,
  first_name VARCHAR(255),
  last_name VARCHAR(255),
  email VARCHAR(255),
  password TEXT NOT NULL
);

--IDEAS TABLE FOR USER TO CRUD
CREATE TABLE IF NOT EXISTS posts (
  id BIGSERIAL PRIMARY KEY,
  user_id INT REFERENCES users,
  description TEXT NOT NULL,
  image VARCHAR(255),
  date_uploaded TIMESTAMP NOT NULL DEFAULT NOW()
);

